### ISSUE TITLE
Automatic creation of RDS backup instance should be optional

### ISSUE THREAD

**Issue by kevinjswinton** [k2s/xtbackup#68]
When running xtbackup against an RDS instance, it should be possible to tell xtbackup *not* to fire up another RDS instance. (It isn't clear from existing documentation if this is possible - and a quick glance of the code suggests this isn't the case).

**Comment by k2s** [comment]
xtbackup contains two mysql drivers:
* [mysql](http://k2s.github.io/xtbackup/tutorial/mysql/file/mysql-to-file.html) - connects to MySQL server and creates backup for it 
* [mysqlAmazonRds](http://k2s.github.io/xtbackup/tutorial/mysql/rds/s3/amazon-rds-to-s3.html) - does exactly the same as mysql, but uses RDS snapshots to create consistent in-time backups

so if you don't want to create temporary RDS instance from snapshot you should simply use the mysql driver.
